import { Project, BoqItem, RfqPackage, SupplierBid, PurchaseOrder } from '@/types/procurement';

export const INITIAL_PROJECT: Project = {
  id: 'proj-marrakech-01',
  code: 'PRJ-MHP-2026',
  name: 'Marrakech Hospitality Project',
  location: 'Marrakech Palm Grove, Morocco',
  budgetMAD: 82400000, // MAD 82.4M
  spentMAD: 34150000,
  currency: 'MAD',
  status: 'tender_active',
  totalBoqItems: 2481, // 2,481 items
  packagesCount: 27,   // 27 packages
  rfqsCount: 14,       // 14 suppliers
  awardedCount: 11,
  completionDate: 'Q4 2027',
  leadConsultant: 'Atelier K+A Architecture & Engineering',
  createdAt: '2026-02-15',
  image: '/images/hero-tower.jpg',
};

export const INITIAL_PROJECTS: Project[] = [
  INITIAL_PROJECT,
  {
    id: 'proj-casablanca-02',
    code: 'PRJ-CFC-2026',
    name: 'Tour Casablanca Finance City',
    location: 'Casablanca Finance City (CFC), Morocco',
    budgetMAD: 145000000, // MAD 145M
    spentMAD: 62800000,
    currency: 'MAD',
    status: 'in_execution',
    totalBoqItems: 4120,
    packagesCount: 36,
    rfqsCount: 28,
    awardedCount: 22,
    completionDate: 'Q2 2028',
    leadConsultant: 'Foster + Partners / BTP Ingénierie Maroc',
    createdAt: '2025-11-10',
    image: '/images/market-trades.jpg',
  },
  {
    id: 'proj-tangier-03',
    code: 'PRJ-TMP-2026',
    name: 'Tangier Med Logistics Hub',
    location: 'Tangier Automotive City & Port Zone, Morocco',
    budgetMAD: 68500000, // MAD 68.5M
    spentMAD: 19400000,
    currency: 'MAD',
    status: 'tender_active',
    totalBoqItems: 1850,
    packagesCount: 19,
    rfqsCount: 16,
    awardedCount: 6,
    completionDate: 'Q1 2027',
    leadConsultant: 'Tanger Port Authority Engineering',
    createdAt: '2026-01-20',
    image: '/images/site-inspection.jpg',
  },
];

export const SAMPLE_BOQ_ITEMS: BoqItem[] = [
  {
    id: 'boq-001',
    itemNumber: '04.01.01',
    packageCode: 'PKG-HVAC-04',
    packageName: 'HVAC Chiller & Air Handling Systems',
    category: 'MEP & HVAC',
    description: 'Centrifugal Water-Cooled Water Chiller 450 TR, VFD Driven, R-1233zd(E) Eco Refrigerant',
    specification: 'ASHRAE 90.1 Compliant, Min COP 6.8, Integrated Modbus/BACnet BMS gateway',
    unit: 'Unit',
    quantity: 2,
    estimatedRateMAD: 850000,
    totalEstimatedMAD: 1700000,
    leadTimeWeeks: 16,
    isLongLead: true,
  },
  {
    id: 'boq-002',
    itemNumber: '04.01.02',
    packageCode: 'PKG-HVAC-04',
    packageName: 'HVAC Chiller & Air Handling Systems',
    category: 'MEP & HVAC',
    description: 'Variable Air Volume (VAV) Air Handling Units with Thermal Recovery Wheel 12,000 CFM',
    specification: 'Double-wall casing 50mm PU insulation, EC plug fans, Eurovent Certified Class A',
    unit: 'Unit',
    quantity: 4,
    estimatedRateMAD: 145000,
    totalEstimatedMAD: 580000,
    leadTimeWeeks: 12,
    isLongLead: true,
  },
  {
    id: 'boq-003',
    itemNumber: '04.02.01',
    packageCode: 'PKG-HVAC-04',
    packageName: 'HVAC Chiller & Air Handling Systems',
    category: 'MEP & HVAC',
    description: 'Chilled Water Circulation Pumps 65 m3/h @ 32m Head with Integrated Inverter',
    specification: 'Cast iron volute, Stainless steel AISI 316 impeller, IE4 super premium motor',
    unit: 'Unit',
    quantity: 3,
    estimatedRateMAD: 48000,
    totalEstimatedMAD: 144000,
    leadTimeWeeks: 8,
    isLongLead: false,
  },
  {
    id: 'boq-004',
    itemNumber: '04.02.04',
    packageCode: 'PKG-HVAC-04',
    packageName: 'HVAC Chiller & Air Handling Systems',
    category: 'MEP & HVAC',
    description: 'Pre-insulated Welded Seamless Steel Pipework DN150 Schedule 40 with Phenolic Foam jacket',
    specification: 'ASTM A53 Grade B, class 1 fire rated vapor barrier cladding',
    unit: 'Linear Meter',
    quantity: 320,
    estimatedRateMAD: 410,
    totalEstimatedMAD: 131200,
    leadTimeWeeks: 4,
    isLongLead: false,
  },
  {
    id: 'boq-005',
    itemNumber: '07.01.01',
    packageCode: 'PKG-FACADE-07',
    packageName: 'Curtain Wall & Architectural Glazing',
    category: 'Façade & Envelope',
    description: 'Unitized Double Glazed Thermal Break Aluminum Curtain Wall System (Low-E 6/16/6)',
    specification: 'U-value <= 1.4 W/m2K, Acoustic rating RW 42dB, EN 13830 certified',
    unit: 'Square Meter',
    quantity: 1840,
    estimatedRateMAD: 2200,
    totalEstimatedMAD: 4048000,
    leadTimeWeeks: 18,
    isLongLead: true,
  },
  {
    id: 'boq-006',
    itemNumber: '02.03.11',
    packageCode: 'PKG-CIVIL-02',
    packageName: 'Reinforced Concrete Superstructure',
    category: 'Civil & Structural',
    description: 'High Performance Ready-Mix Concrete C35/45 with Silica Fume for Sub-Saline Ground Resistance',
    specification: 'NM 10.1.008 standard, slump class S4, 28-day cylinder compressive strength >= 35MPa',
    unit: 'Cubic Meter',
    quantity: 4200,
    estimatedRateMAD: 980,
    totalEstimatedMAD: 4116000,
    leadTimeWeeks: 2,
    isLongLead: false,
  },
  {
    id: 'boq-007',
    itemNumber: '09.02.05',
    packageCode: 'PKG-FINISH-09',
    packageName: 'Porcelain Stoneware & Natural Marble Tiling',
    category: 'Finishes',
    description: 'First Choice Calacatta Gold Moroccan Polished Marble Slabs 20mm thickness Book-Matched',
    specification: 'Water absorption <= 0.2%, flexural strength >= 14 MPa, dry honed treatment',
    unit: 'Square Meter',
    quantity: 950,
    estimatedRateMAD: 820,
    totalEstimatedMAD: 779000,
    leadTimeWeeks: 10,
    isLongLead: true,
  },
];

export const INITIAL_PACKAGES: RfqPackage[] = [
  {
    id: 'pkg-04',
    packageCode: 'PKG-HVAC-04',
    title: 'HVAC Chiller & Air Handling Systems',
    trade: 'Mechanical & Climatic Engineering',
    projectId: 'proj-marrakech-01',
    projectName: 'Marrakech Hospitality Project',
    budgetMAD: 2600000,
    deadline: '2026-10-15',
    status: 'evaluating',
    itemsCount: 18,
    invitedSuppliers: 5,
    submittedBids: 3,
    specStandard: 'ASHRAE 90.1 / Eurovent Class A',
  },
  {
    id: 'pkg-07',
    packageCode: 'PKG-FACADE-07',
    title: 'Curtain Wall & Architectural Glazing',
    trade: 'Building Envelope & Metalworks',
    projectId: 'proj-marrakech-01',
    projectName: 'Marrakech Hospitality Project',
    budgetMAD: 4200000,
    deadline: '2026-10-22',
    status: 'bids_received',
    itemsCount: 24,
    invitedSuppliers: 4,
    submittedBids: 2,
    specStandard: 'EN 13830 / CWCT Standard',
  },
  {
    id: 'pkg-02',
    packageCode: 'PKG-CIVIL-02',
    title: 'Structural Steel Trusses & Decking',
    trade: 'Structural Engineering',
    projectId: 'proj-marrakech-01',
    projectName: 'Marrakech Hospitality Project',
    budgetMAD: 5800000,
    deadline: '2026-09-30',
    status: 'awarded',
    itemsCount: 32,
    invitedSuppliers: 3,
    submittedBids: 3,
    specStandard: 'Eurocode 3 / EN 1090-2 EXC3',
  },
  {
    id: 'pkg-09',
    packageCode: 'PKG-FINISH-09',
    title: 'Porcelain Stoneware & Natural Marble Tiling',
    trade: 'Architectural Finishes',
    projectId: 'proj-marrakech-01',
    projectName: 'Marrakech Hospitality Project',
    budgetMAD: 1200000,
    deadline: '2026-11-05',
    status: 'issued',
    itemsCount: 42,
    invitedSuppliers: 6,
    submittedBids: 1,
    specStandard: 'ISO 13006 Group BIa',
  },
];

// Exact prompt specification for Section 9 & Section 6:
// Supplier A: MAD 2.41M, 100% specification match
// Supplier B: MAD 2.27M, 92% specification match, Transport excluded
// Supplier C: MAD 2.49M, 100% specification match, 90-day payment
export const INITIAL_BIDS_PKG04: SupplierBid[] = [
  {
    id: 'bid-001',
    rfqId: 'pkg-04',
    supplierName: 'Atlas Clim Systems S.A.',
    supplierCode: 'SUP-MA-1082',
    country: 'Morocco (Casablanca)',
    channel: 'Portal',
    quotedTotalMAD: 2410000, // MAD 2.41M
    normalizedTotalMAD: 2410000,
    specMatchPercentage: 100, // 100% specification match
    transportIncluded: true,
    transportAdjustmentMAD: 0,
    paymentTerms: '60 days end of month',
    paymentTermScore: 85,
    deliveryWeeks: 14,
    complianceStatus: 'Full Match',
    notes: 'Official Trane / Daikin Tier-1 distributor. Includes on-site commissioning, factory acceptance testing, and 24-month warranty.',
    exclusions: [],
    substitutions: [],
    isRecommended: true,
  },
  {
    id: 'bid-002',
    rfqId: 'pkg-04',
    supplierName: 'Maghreb Clim Solutions SARL',
    supplierCode: 'SUP-MA-0941',
    country: 'Morocco (Tangier Free Zone)',
    channel: 'WhatsApp',
    quotedTotalMAD: 2270000, // MAD 2.27M (lowest headline price!)
    normalizedTotalMAD: 2455000, // Normalized for excluded transport + substitute penalty
    specMatchPercentage: 92, // 92% specification match
    transportIncluded: false, // Transport excluded!
    transportAdjustmentMAD: 185000, // +MAD 185k transport & crane unloading
    paymentTerms: '30% advance, 70% before shipping',
    paymentTermScore: 50,
    deliveryWeeks: 18,
    complianceStatus: 'Minor Discrepancy',
    notes: 'Quotation sent via WhatsApp PDF. Transport from Tangier to Marrakech site excluded. EC plug fan brand substituted with Chinese OEM equivalent.',
    exclusions: ['Site delivery to Marrakech (Ex-Works Tangier)', 'Crane hoisting onto plant roof', 'First year preventive maintenance'],
    substitutions: [
      { original: 'Eurovent Class A Fan', proposed: 'Generic Centrifugal Fan (Non-Eurovent)', variance: '-8% efficiency delta' }
    ],
    isRecommended: false,
  },
  {
    id: 'bid-003',
    rfqId: 'pkg-04',
    supplierName: 'Sahara Thermal Technologies',
    supplierCode: 'SUP-MA-1205',
    country: 'Morocco (Agadir / Marrakech)',
    channel: 'Email',
    quotedTotalMAD: 2490000, // MAD 2.49M
    normalizedTotalMAD: 2462000, // Adjusted for working capital benefit of 90 days credit
    specMatchPercentage: 100, // 100% specification match
    transportIncluded: true,
    transportAdjustmentMAD: 0,
    paymentTerms: '90-day deferred payment', // 90-day payment
    paymentTermScore: 98,
    deliveryWeeks: 15,
    complianceStatus: 'Full Match',
    notes: 'Includes Carrier Eurovent certified equipment. Extended 90-day payment terms provide working capital relief for the general contractor.',
    exclusions: [],
    substitutions: [],
    isRecommended: false,
  },
];

export const INITIAL_PURCHASE_ORDER: PurchaseOrder = {
  id: 'po-mhp-089',
  poNumber: 'PO-MHP-2026-089',
  rfqId: 'pkg-04',
  projectId: 'proj-marrakech-01',
  projectName: 'Marrakech Hospitality Project',
  supplierName: 'Atlas Clim Systems S.A.',
  supplierContact: 'Youssef El Mansouri (Commercial Director) - +212 522 884 900',
  supplierAddress: 'Zone Industrielle Sidi Maârouf, Lot 44, Casablanca, Morocco',
  issueDate: '2026-09-24',
  deliveryDate: '2026-12-18',
  totalAmountMAD: 2410000,
  taxAmountMAD: 482000, // 20% Moroccan VAT
  grandTotalMAD: 2892000,
  retentionPercentage: 10,
  paymentTerms: '60 days end of month upon site inspection milestone approval',
  deliveryLocation: 'Marrakech Palm Grove Luxury Resort Site, Gate 2 Heavy Equipment Bay, Marrakech',
  status: 'issued',
  authorizedBy: 'Tariq Benjelloun, Chief Procurement Officer',
  items: [
    {
      itemNumber: '04.01.01',
      description: 'Centrifugal Water-Cooled Water Chiller 450 TR, VFD Driven, R-1233zd(E) Eco Refrigerant',
      unit: 'Unit',
      quantity: 2,
      unitPriceMAD: 820000,
      totalMAD: 1640000,
    },
    {
      itemNumber: '04.01.02',
      description: 'Variable Air Volume (VAV) Air Handling Units with Thermal Recovery Wheel 12,000 CFM',
      unit: 'Unit',
      quantity: 4,
      unitPriceMAD: 135000,
      totalMAD: 540000,
    },
    {
      itemNumber: '04.02.01',
      description: 'Chilled Water Circulation Pumps 65 m3/h @ 32m Head with Integrated Inverter',
      unit: 'Unit',
      quantity: 3,
      unitPriceMAD: 46000,
      totalMAD: 138000,
    },
    {
      itemNumber: '04.02.04',
      description: 'Pre-insulated Welded Seamless Steel Pipework DN150 Schedule 40 with Phenolic Foam jacket',
      unit: 'Linear Meter',
      quantity: 320,
      unitPriceMAD: 287.5,
      totalMAD: 92000,
    },
  ],
};
